# Generated by Django 3.2.5 on 2021-07-07 09:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.TextField(max_length=300)),
                ('brand', models.CharField(max_length=30)),
                ('purchase_date', models.DateField(default=datetime.datetime(2021, 7, 7, 11, 12, 34, 866955))),
                ('qualification', models.TextField(max_length=300)),
                ('room', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Gerät',
                'verbose_name_plural': 'Geräte',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(choices=[('dqi18', 'DQI18'), ('dqi19', 'DQI19'), ('dqi20', 'DQI20'), ('dqi21', 'DQI21')], max_length=5)),
                ('letter_of_acceptance', models.BooleanField(default=False)),
                ('induction_course', models.BooleanField(default=False)),
                ('course_date', models.DateField(blank=True)),
                ('teacher', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2021, 7, 7, 11, 12, 34, 867954))),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buchungssystem.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buchungssystem.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AnnulatedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2021, 7, 7, 11, 12, 34, 868953))),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buchungssystem.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buchungssystem.userprofile')),
            ],
        ),
    ]
