# Generated by Django 3.2.5 on 2021-07-07 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buchungssystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annulatedappointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 11, 13, 9, 929285)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 11, 13, 9, 929285)),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 11, 13, 9, 927286)),
        ),
    ]
