# Generated by Django 3.2.5 on 2021-07-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buchungssystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annulatedappointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='annulatedappointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='annulatedappointment',
            name='start_time',
        ),
        migrations.AddField(
            model_name='annulatedappointment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ende'),
        ),
        migrations.AddField(
            model_name='annulatedappointment',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='annulatedappointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kursbelegungsdatum'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
