# Generated by Django 3.0.5 on 2021-07-12 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Buchungssystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 12, 6, 56, 15, 636057, tzinfo=utc), null=True, verbose_name='Kursbelegungsdatum'),
        ),
    ]
